name: xml_rpc
version: 0.2.2
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A library to communicate through the XML-RPC protocol.
homepage: https://github.com/a14n/dart-xmlrpc
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'
dependencies:
  http: ^0.11.0
  meta: ^1.1.5
  xml: ^3.0.0
dev_dependencies:
  test: ^1.3.0
